-- 现场 31 列全类型矩阵（照 app.alltypes 的真实定义，§4.1.1）
CREATE TABLE perf_doctor_golden.alltypes31 (
  c_long INT NOT NULL,
  c_tiny TINYINT,
  c_utiny TINYINT UNSIGNED,
  c_short SMALLINT,
  c_int24 MEDIUMINT,
  c_ulong INT UNSIGNED,
  c_longlong BIGINT,
  c_float FLOAT,
  c_double DOUBLE,
  c_dec DECIMAL(18,6),
  c_date DATE,
  c_year YEAR,
  c_ts TIMESTAMP(6) NULL,
  c_dt DATETIME(3),
  c_time TIME(2),
  c_char CHAR(40),
  c_binary BINARY(20),
  c_varchar VARCHAR(300),
  c_varbinary VARBINARY(100),
  c_tinytext TINYTEXT,
  c_text TEXT,
  c_mediumtext MEDIUMTEXT,
  c_longtext LONGTEXT,
  c_tinyblob TINYBLOB,
  c_blob BLOB,
  c_mediumblob MEDIUMBLOB,
  c_longblob LONGBLOB,
  c_json JSON,
  c_bit BIT(13),
  c_enum ENUM('a','b','c'),
  c_set SET('x','y','z'),
  PRIMARY KEY (c_long)
) ENGINE=InnoDB
