-- 除地理类型外的全部列类型（整数五档含 unsigned、浮点、DECIMAL、时间、字符/二进制、TEXT/BLOB 家族、JSON、BIT、ENUM、SET）
CREATE TABLE perf_doctor_golden.alltypes (
  c_tiny TINYINT NOT NULL,
  c_utiny TINYINT UNSIGNED NOT NULL,
  c_short SMALLINT NOT NULL,
  c_ushort SMALLINT UNSIGNED NOT NULL,
  c_int24 MEDIUMINT NOT NULL,
  c_uint24 MEDIUMINT UNSIGNED NOT NULL,
  c_long INT NOT NULL,
  c_ulong INT UNSIGNED NOT NULL,
  c_longlong BIGINT NOT NULL,
  c_ulonglong BIGINT UNSIGNED NOT NULL,
  c_float FLOAT NOT NULL,
  c_double DOUBLE NOT NULL,
  c_dec DECIMAL(18,6) NOT NULL,
  c_date DATE NOT NULL,
  c_year YEAR NOT NULL,
  c_time TIME NOT NULL,
  c_dt DATETIME(3) NOT NULL,
  c_ts TIMESTAMP(6) NULL,
  c_char CHAR(10) NOT NULL,
  c_bin BINARY(8) NOT NULL,
  c_vchar VARCHAR(64) NOT NULL,
  c_vbin VARBINARY(64) NOT NULL,
  c_text TEXT NOT NULL,
  c_json JSON NOT NULL,
  c_bit BIT(13) NOT NULL,
  c_enum ENUM('a','b') NOT NULL,
  c_set SET('x','y') NOT NULL,
  PRIMARY KEY (c_long)
) ENGINE=InnoDB
